# Permalinks
permalink:        pretty

# Your site's full URL, e.g. "https://my-site.com"
url: "http://less-by-choice.com"

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

# Site settings
title: less by choice
description: "I've been choosing minimalism for freedom and clarity. Join the conversation."

author:
  name:    'Esther'

  # This photo will be used in the about section
  photo:   http://estherleytush.com/assets/images/headshot.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:  "I'm a career switcher and I'm working on paying down a huge amount of debt. I've chosen minimalism because I discovered kinship with simple living, and clearing away stuff in order to give more space for what matters."

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Adding static pages through `_static/` folder
include: ['_static']

# Adding an xml sitemap
gems:
  - jekyll-sitemap
